spring:
  datasource:
    url: jdbc:mysql://intellij.xyz:3306/stream_share?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: Whp98Mysql
debug: true
mybatis:
  type-aliases-package: xyz.intellij.appsharestream.model
  config-location: classpath:mybatis.xml